export const GET_HIST_DATA = 'GET_HIST_DATA';
export const GET_PIE_DATA = 'GET_PIE_DATA';
export const GET_COUNTRY_DATA='GET_COUNTRY_DATA';
export const GET_CONTINENT_DATA='GET_CONTINENT_DATA';
export const GET_LINE_DATA='GET_LINE_DATA';
export const GET_COUNTRY_STATS='GET_COUNTRY_STATS';